# Generated by Django 5.2.1 on 2025-06-04 04:33

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size])),
                ('prescription_file', models.FileField(upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size])),
                ('medicines_name', models.TextField(help_text='Comma-separated medicine names and dosages')),
                ('prescribed_tests', models.TextField(help_text='comma separated test  names')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
