# Generated by Django 5.2.1 on 2025-05-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_left', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scheduled_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.CharField(max_length=255)),
                ('prescription_file', models.CharField(max_length=255)),
                ('scheduled_on', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.doctorprofile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.userprofile')),
                ('prescribed_medicines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicines')),
                ('prescribed_tests', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tests')),
            ],
        ),
    ]
