# Generated by Django 5.2.1 on 2025-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_medicines_tests_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='prescription_file',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reports',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
