# Generated by Django 5.2.1 on 2025-05-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_appointments_prescription_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='catagory_id',
            new_name='category_id',
        ),
    ]
