# Generated by Django 4.2.21 on 2025-06-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
        ),
    ]
