# Generated by Django 4.2.21 on 2025-06-07 18:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_medicalrecord_medical_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medicines_name',
            field=models.TextField(blank=True, help_text='Comma-separated medicine names and dosages', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescribed_tests',
            field=models.TextField(blank=True, help_text='comma separated test  names', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
    ]
