# Generated by Django 4.2.21 on 2025-05-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_catagory_id_appointments_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.IntegerField(default=0, verbose_name=((0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'))),
        ),
    ]
