# Generated by Django 5.2.1 on 2025-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_familymember_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
