# Generated by Django 5.2.1 on 2025-05-30 15:35

import uuid
from django.db import migrations

def assign_uuids(apps, schema_editor):
    FamilyMember = apps.get_model('main', 'FamilyMember')
    for member in FamilyMember.objects.all():
        if not member.uuid:
            member.uuid = uuid.uuid4()
            member.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_familymember_uuid'),
    ]

    operations = [
        migrations.RunPython(assign_uuids),
    ]
