# Generated by Django 5.2.1 on 2025-05-30 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250530_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
