# Generated by Django 5.2.1 on 2025-05-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_familymember_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='prescription_file',
            field=models.FileField(max_length=255, null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reports',
            field=models.FileField(max_length=255, null=True, upload_to='reports/'),
        ),
    ]
