# Generated by Django 5.2.1 on 2025-05-31 03:56

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_appointments_prescription_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='prescribed_medicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.medicines'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='prescribed_tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tests'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='prescription_file',
            field=models.FileField(max_length=255, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reports',
            field=models.FileField(max_length=255, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
    ]
