# Generated by Django 5.2.1 on 2025-05-31 04:24

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_appointments_prescribed_medicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reports',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to_unique, validators=[main.models.validate_file_size]),
        ),
    ]
